2025-01-01 17:45:58,408 - WARNING : Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Users\Warlav\PycharmProjects\UrbanAcademy\module_12\tests_12_4.py", line 72, in test_run
    walker = Runner(3)
  File "C:\Users\Warlav\PycharmProjects\UrbanAcademy\module_12\tests_12_4.py", line 10, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2025-01-01 17:45:58,410 - WARNING : Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\Users\Warlav\PycharmProjects\UrbanAcademy\module_12\tests_12_4.py", line 61, in test_walk
    walker = Runner('Stepan', -5)
  File "C:\Users\Warlav\PycharmProjects\UrbanAcademy\module_12\tests_12_4.py", line 15, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
